Pidev_Jee-web/src/main/java/tn/esprit/pidev/ManagedBean/EntrepriseBean.java
package tn.esprit.pidev.ManagedBean;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import model.Entrepris;
import model.Entretien;
import tn.esprit.pidev.services.EntrepriseService;
import tn.esprit.pidev.services.EntretienService;
@ManagedBean(name="entrepriseBean")
@SessionScoped 
public class EntrepriseBean implements Serializable {
	private int id;
private String nomEntreprise;
private String descriptionEntre;
private int nbrEmploye;
private Date date_Created;
private Date date_Modified;
private Date date_Deleted;
private boolean isDeleted;

public int getId() {
	return id;
}
public void setId(int id) {
	this.id = id;
}

public boolean isDeleted() {
	return isDeleted;
}
public void setDeleted(boolean isDeleted) {
	this.isDeleted = isDeleted;
}
public String getNomEntreprise() {
	return nomEntreprise;
}
public void setNomEntreprise(String nomEntreprise) {
	this.nomEntreprise = nomEntreprise;
}
public String getDescriptionEntre() {
	return descriptionEntre;
}
public void setDescriptionEntre(String descriptionEntre) {
	this.descriptionEntre = descriptionEntre;
}
public int getNbrEmploye() {
	return nbrEmploye;
}
public void setNbrEmploye(int nbrEmploye) {
	this.nbrEmploye = nbrEmploye;
}
public Date getDate_Created() {
	return date_Created;
}
public void setDate_Created(Date date_Created) {
	this.date_Created = date_Created;
}
public Date getDate_Modified() {
	return date_Modified;
}
public void setDate_Modified(Date date_Modified) {
	this.date_Modified = date_Modified;
}
public Date getDate_Deleted() {
	return date_Deleted;
}
public void setDate_Deleted(Date date_Deleted) {
	this.date_Deleted = date_Deleted;
}
@EJB
EntrepriseService es;

public void addEntretien() throws ParseException
{
	es.ajouterEntreprise(new Entrepris(date_Created,date_Deleted,date_Modified,descriptionEntre,isDeleted,nbrEmploye,nomEntreprise));
	}

public void ajouterEntreprise()throws ParseException
{SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
	
Entrepris e=new Entrepris(date_Created,date_Deleted,date_Modified,descriptionEntre,isDeleted,nbrEmploye,nomEntreprise);
e.setIsDeleted(true);
es.ajouterEntreprise(e);


}

}

Pidev_Jee-web/src/main/webapp/Pages/Admin/AfficherEntretien.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">
<ui:define name="title">Liste des Entretiens:</ui:define>
<ui:define name="content">

<h:panelGroup columns="2">
<h:form>
<table>


<tr>
<td>
    <h:outputText value="Date Debut"/>
</td>
<td>
     <h:inputText id="date" value="#{entretienBean.dateDebut}">
              <f:convertDateTime pattern="dd-MM-yyyy"/>
     </h:inputText>
</td>
<td>
     <h:message for="date" style="color:red"/>
</td>
</tr>
<tr>
<td>
    <h:outputText value="Date fin"/>
</td>
<td>
     <h:inputText id="date1" value="#{entretienBean.dateFin}">
              <f:convertDateTime pattern="dd-MM-yyyy"/>
     </h:inputText>
</td>
<td>
     <h:message for="date1" style="color:red"/>
</td>
</tr>
<tr><td>
<h:outputText value="Théme"/></td> <td><h:inputText value="#{entretienBean.theme}"/></td></tr>
<tr><td>
<h:outputText value="Location"/></td> <td><h:inputText value="#{entretienBean.location}"/></td></tr>

 
 

<tr><td colspan="2"> 
<h:commandButton value="Ajouter Employé" action="#{entretienBean.ajouterEntretien()}" />
<h:commandButton value="Mettre A jour Employé" action="#{entretienBean.updateEntretien()}" />
</td></tr>
</table>
</h:form>
</h:panelGroup>
	


<h:panelGroup columns="2"> 
<h:form> 
<table>
<h:dataTable value="#{entretienBean.entretiens}" var="entretien" border="1">
<h:column><f:facet name="header"><h:outputText value="Date_Debut" /></f:facet> 
<h:outputText value="#{entretien.dateDebut}" /></h:column>
<h:column><f:facet name="header"><h:outputText value="Date_Fin" /></f:facet> 
<h:outputText value="#{entretien.dateFin}" /></h:column>
<h:column><f:facet name="header"><h:outputText value="Location" /></f:facet> 
<h:outputText value="#{entretien.location}" /></h:column>
<h:column><f:facet name="header"><h:outputText value="Théme" /></f:facet> 
<h:outputText value="#{entretien.theme}" /></h:column>
<h:column> <f:facet name="header"><h:outputText value="Action" /></f:facet> 	
<h:commandButton action="#{entretienBean.removeEntretien(entretien.id)}" value="Supprimer" /> 
<h:commandButton action="#{entretienBean.displayEmploye(entretien)}" value="Afficher" />
</h:column>


</h:dataTable> 
</table>
</h:form>
 </h:panelGroup>


</ui:define>
</ui:composition>

Pidev_Jee-web/src/main/webapp/Pages/Admin/AjouterEntreprise.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">
<ui:define name="title">Ajouter Contrat à Un Employe</ui:define>
<ui:define name="content">


	

<h:form>

</h:form>
<h:panelGroup columns="2">
<h:form>
<table>

<tr>
<td>
    <h:outputText value="Nom Entreprise"/>
</td>
<td>
     <h:inputText id="nom" value="#{entrepriseBean.nomEntreprise}">
             
     </h:inputText>
</td>

</tr>
<tr>
<td>
    <h:outputText value="Description "/>
</td>
<td>
     <h:inputText id="date1" value="#{entrepriseBean.descriptionEntre}">
              
     </h:inputText>
</td>

</tr>
<tr><td><h:outputText value="nombreEmp"></h:outputText></td> 

<td><h:inputText value="#{entrepriseBean.nbrEmploye}"/></td>

</tr>
<tr><td>
<h:outputText value="isDeleted"/></td> 
<td><h:inputText value="#{entrepriseBean.deleted}"/></td></tr>

 
 

<tr><td colspan="2"> 
<h:commandButton value="Ajouter Entretien" action="#{entrepriseBean.ajouterEntreprise()}" />

</td></tr>
</table>
</h:form>
</h:panelGroup>


</ui:define>
</ui:composition>

Pidev_Jee-web/src/main/webapp/Pages/Admin/AjouterEntretien.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">
<ui:define name="title">Ajouter Contrat à Un Employe</ui:define>
<ui:define name="content">


	

<h:form>

</h:form>
<h:panelGroup columns="2">
<h:form>
<table>

<tr>
<td>
    <h:outputText value="Date Debut"/>
</td>
<td>
     <h:inputText id="date" value="#{entretienBean.dateDebut}">
              <f:convertDateTime pattern="dd-MM-yyyy"/>
     </h:inputText>
</td>
<td>
     <h:message for="date" style="color:red"/>
</td>
</tr>
<tr>
<td>
    <h:outputText value="Date fin"/>
</td>
<td>
     <h:inputText id="date1" value="#{entretienBean.dateFin}">
              <f:convertDateTime pattern="dd-MM-yyyy"/>
     </h:inputText>
</td>
<td>
     <h:message for="date1" style="color:red"/>
</td>
</tr>
<tr><td><h:outputText value="Location"></h:outputText></td> 

<td><h:inputText value="#{entretienBean.location}"/></td>

</tr>
<tr><td>
<h:outputText value="Type"/></td> 
<td><h:inputText value="#{entretienBean.theme}"/></td></tr>
<tr><td>
 <h:outputText value="Quiz"/></td>
 <td>
 <h:selectOneMenu value="#{entretienBean.quiz_id}">
<f:selectItems  
value="#{entretienBean.l_quizs}"
var="quiz" 
itemValue="#{quiz.id}" 
itemLabel="#{quiz}" 
/>
</h:selectOneMenu>


</td>
</tr>

 
 

<tr><td colspan="2"> 
<h:commandButton value="Ajouter Entretien" action="#{entretienBean.ajouterEntretien()}" />

</td></tr>
</table>
</h:form>
</h:panelGroup>


</ui:define>
</ui:composition>

Pidev_Jee-web/src/main/webapp/Pages/Admin/GestionQuestion.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">
<ui:define name="title">Gestion des questions:</ui:define>
<ui:define name="content">

<h:panelGroup columns="2">
<h:form>
<table>



<tr><td>
<h:outputText value="Content"/></td> <td><h:inputText value="#{questionBean.content_Question}"/></td></tr>
<tr><td>
<h:outputText value="Choix 1"/></td> <td><h:inputText value="#{questionBean.choice1}"/></td></tr>
<tr><td>
<h:outputText value="Choix 2"/></td> <td><h:inputText value="#{questionBean.choice2}"/></td></tr>
 
<tr><td>
<h:outputText value="Choix 3"/></td> <td><h:inputText value="#{questionBean.choice3}"/></td></tr> 

<tr><td colspan="2"> 
<h:commandButton value="Ajouter Quiz" action="#{questionBean.ajouterQuestion}" />
<h:commandButton value="Mettre A jour Employé" action="#{questionBean.updateQuestion}" />
</td></tr>
</table>
</h:form>
</h:panelGroup>

<h:panelGroup columns="2"> 
<h:form> 
<table>
<h:dataTable value="#{questionBean.questions}" var="question" border="1">

<h:column><f:facet name="header"><h:outputText value="Content" /></f:facet> 
<h:outputText value="#{question.content_Question}" /></h:column>
<h:column><f:facet name="header"><h:outputText value="Choice 1" /></f:facet> 
<h:outputText value="#{question.choice1}" /></h:column>
<h:column><f:facet name="header"><h:outputText value="Choice 2" /></f:facet> 
<h:outputText value="#{question.choice2}" /></h:column>
<h:column><f:facet name="header"><h:outputText value="Choice 3" /></f:facet> 
<h:outputText value="#{question.choice3}" /></h:column>
<h:column> <f:facet name="header"><h:outputText value="Action" /></f:facet> 	
<h:commandButton action="#{questionBean.removeQuestion(question.id_Question)}" value="Supprimer" /> 
<h:commandButton action="#{questionBean.displayQuestion(question)}" value="Afficher" />
</h:column>


</h:dataTable> 
</table>
</h:form>
 </h:panelGroup>

	
</ui:define>
</ui:composition>

Pidev_Jee-web/src/main/webapp/Pages/Admin/GestionQuiz.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">
<ui:define name="title">Liste des Entretiens:</ui:define>
<ui:define name="content">

<h:panelGroup columns="2">
<h:form>
<table>



<tr><td>
<h:outputText value="Nom_Quiz"/></td> <td><h:inputText value="#{quizBean.name_Quiz}"/></td></tr>
<tr><td>
<h:outputText value="Points_Tot"/></td> <td><h:inputText value="#{quizBean.nbr_Point_Tolal}"/></td></tr>
<tr><td>
<h:outputText value="Nbr_Question"/></td> <td><h:inputText value="#{quizBean.nbr_Question}"/></td></tr>
 
 

<tr><td colspan="2"> 
<h:commandButton value="Ajouter Quiz" action="#{quizBean.ajouterQuiz()}" />
<h:commandButton value="Mettre A jour Employé" action="#{quizBean.updateQuiz()}" />
</td></tr>
</table>
</h:form>
</h:panelGroup>

<h:panelGroup columns="2"> 
<h:form> 
<table>
<h:dataTable value="#{quizBean.quizs}" var="quiz" border="1">

<h:column><f:facet name="header"><h:outputText value="Nom_Quiz" /></f:facet> 
<h:outputText value="#{quiz.name_Quiz}" /></h:column>
<h:column><f:facet name="header"><h:outputText value="Points_Tot" /></f:facet> 
<h:outputText value="#{quiz.nbr_Point_Tolal}" /></h:column>
<h:column><f:facet name="header"><h:outputText value="Nbr_Question" /></f:facet> 
<h:outputText value="#{quiz.nbr_Question}" /></h:column>
<h:column> <f:facet name="header"><h:outputText value="Action" /></f:facet> 	
<h:commandButton action="#{quizBean.removeQuiz(quiz.id)}" value="Supprimer" /> 
<h:commandButton action="#{quizBean.displayQuiz(quiz)}" value="Afficher" />
</h:column>


</h:dataTable> 
</table>
</h:form>
 </h:panelGroup>

	
</ui:define>
</ui:composition>

Pidev_Jee-web/src/main/webapp/Pages/Admin/welcome.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">
<ui:define name="title">Welcom</ui:define>
<ui:define name="content">
Welcom #{loginBean.employe.nom} #{loginBean.employe.prenom} 

	

<h:form>
<h:commandButton action="#{loginBean.doLogout()}" values="logout"/>
<h:link outcome="/Pages/Admin/AjouterContrat" value="AddEMp"/>
<h:link outcome="/Pages/Admin/GererEmployer" value="Afficher"/>



</h:form>


</ui:define>

</ui:composition>
